#!/bin/bash
# -----------------------------------------------------------------------------
# USAGE:
# ./makequery repo 10
# -----------------------------------------------------------------------------

ROOT="repo"
QUERIES=10

if [ "$1" != "" ]; then
   ROOT=$1
fi
if [ "$2" != "" ]; then
   QUERIES=$2
fi

mkdir ${ROOT}/query -p

for NET in ${ROOT}/*.bif; do
   NAME=$(basename "$NET")
   NAME=${NAME%.bif}

   echo "qevgen -i ${NET} -o ${ROOT}/query/${NAME}.q  -n $QUERIES"
         qevgen -i ${NET} -o ${ROOT}/query/${NAME}.q  -n $QUERIES
   echo "qevgen -i ${NET} -o ${ROOT}/query/${NAME}.ev -n $QUERIES"
         qevgen -i ${NET} -o ${ROOT}/query/${NAME}.ev -n $QUERIES

   echo "libra acve -m ${NET} -o ${ROOT}/model/${NAME}.ac &> ${ROOT}/model/${NAME}.outac"
         libra acve -m ${NET} -o ${ROOT}/model/${NAME}.ac &> ${ROOT}/model/${NAME}.outac
   libra fstats -i ${ROOT}/model/${NAME}.ac &>> ${ROOT}/model/${NAME}.outac
   echo "libra acquery -m ${ROOT}/model/${NAME}.ac -q ${ROOT}/query/${NAME}.q -ev ${ROOT}/query/${NAME}.ev &> ${ROOT}/query/${NAME}.infkey"
         libra acquery -m ${ROOT}/model/${NAME}.ac -q ${ROOT}/query/${NAME}.q -ev ${ROOT}/query/${NAME}.ev &> ${ROOT}/query/${NAME}.infkey
done

