#!/bin/bash
# -----------------------------------------------------------------------------
# USAGE:
# ./makekeys repo
# -----------------------------------------------------------------------------

ROOT="repo"

if [ "$1" != "" ]; then
   ROOT=$1
fi

SOLVER="dai-solver"
for NET in ${ROOT}/*.bif; do
   NAME=$(basename "$NET")
   NAME=${NAME%.bif}
   SEED=0

   MODEL=${ROOT}/query/${NAME}.uai
   EVID=${ROOT}/query/${NAME}.uai.evid
   QUER=${ROOT}/query/${NAME}.uai.quer
   OUT=${ROOT}/query/${NAME}.dailog

   exp-run convert -i ${NET} -o ${MODEL} -t bif2uai
   exp-run convert -i ${ROOT}/query/${NAME}.ev -o ${EVID} -t ev2evid
   exp-run convert -i ${ROOT}/query/${NAME}.q  -o ${QUER} -t ev2evid

   echo "${SOLVER} ${MODEL} ${EVID} ${QUER} &> ${OUT}"
   ${SOLVER} ${MODEL} ${EVID} ${QUER} &> ${OUT}
   echo "${SOLVER} ${MODEL} ${EVID} &>> ${OUT}"
   ${SOLVER} ${MODEL} ${EVID} &>> ${OUT}

done

