#!/bin/bash
# -----------------------------------------------------------------------------
# USAGE:
# ./makequery repo 10
# -----------------------------------------------------------------------------

ROOT="repo"
QUERIES=10

if [ "$1" != "" ]; then
   ROOT=$1
fi
if [ "$2" != "" ]; then
   QUERIES=$2
fi

mkdir ${ROOT}/query -p

for NET in ${ROOT}/*.bif; do
   NAME=$(basename "$NET")
   NAME=${NAME%.bif}

   echo "qevgen -i ${NET} -o ${ROOT}/query/${NAME}.q  -n $QUERIES"
         qevgen -i ${NET} -o ${ROOT}/query/${NAME}.q  -n $QUERIES
   echo "qevgen -i ${NET} -o ${ROOT}/query/${NAME}.ev -n $QUERIES"
         qevgen -i ${NET} -o ${ROOT}/query/${NAME}.ev -n $QUERIES

done

