#!/bin/bash
# -----------------------------------------------------------------------------
# USAGE:
# ./libra-learn <in-dir> <alg> <out-dir>
# alg: cl, bnlearn, acbn, acmn, idspn, mtlearn
# -----------------------------------------------------------------------------

ROOT="repo"
ALG="cl"
OUT="./"

if [ "$1" != "" ]; then
   ROOT=$1
fi
if [ "$2" != "" ]; then
   ALG=$2
fi
if [ "$3" != "" ]; then
   OUT=$3
   mkdir ${OUT} -p
fi

EXT="ac"
for NET in ${ROOT}/*.bif; do
   NAME=$(basename "$NET")
   NAME=${NAME%.bif}

   case "$ALG" in
      "cl" | "bnlearn")
         EXT="bn"
         echo "libra ${ALG} -i ${ROOT}/data/${NAME}.train -o ${OUT}/${NAME}-${ALG}.bn -prior 1 &> ${OUT}/${NAME}-${ALG}.out"
               libra ${ALG} -i ${ROOT}/data/${NAME}.train -o ${OUT}/${NAME}-${ALG}.bn -prior 1 &> ${OUT}/${NAME}-${ALG}.out
      ;;
      "acbn" | "acmn")
         echo "libra ${ALG} -i ${ROOT}/data/${NAME}.train -o ${OUT}/${NAME}-${ALG}.ac          &> ${OUT}/${NAME}-${ALG}.out"
               libra ${ALG} -i ${ROOT}/data/${NAME}.train -o ${OUT}/${NAME}-${ALG}.ac          &> ${OUT}/${NAME}-${ALG}.out
      ;;
      "idspn" | "mtlearn")
         SEED=$(date +%N)
         echo "libra ${ALG} -i ${ROOT}/data/${NAME}.train -o ${OUT}/${NAME}-${ALG}.spn -seed ${SEED} &> ${OUT}/${NAME}-${ALG}.out"
               libra ${ALG} -i ${ROOT}/data/${NAME}.train -o ${OUT}/${NAME}-${ALG}.spn -seed ${SEED} &> ${OUT}/${NAME}-${ALG}.out
         echo "libra spn2ac -m ${OUT}/${NAME}-${ALG}.spn -o ${OUT}/${NAME}-${ALG}.ac &>> ${OUT}/${NAME}-${ALG}.out"
               libra spn2ac -m ${OUT}/${NAME}-${ALG}.spn -o ${OUT}/${NAME}-${ALG}.ac &>> ${OUT}/${NAME}-${ALG}.out
      ;;
   esac

   echo "libra mscore -m ${OUT}/${NAME}-${ALG}.${EXT} -i ${ROOT}/data/${NAME}.test &> ${OUT}/${NAME}-${ALG}.score"
         libra mscore -m ${OUT}/${NAME}-${ALG}.${EXT} -i ${ROOT}/data/${NAME}.test &> ${OUT}/${NAME}-${ALG}.score
done

